version: '3'

services:
  server:
    build: .
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - db
    links:
      - db
  db:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: storage
      MYSQL_HOST: db
    restart: always
    ports:
      - '3306:3306'
