version: '3'

services:
  server:
    build: .
    restart: always
    ports:
      - '8000:8000'
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    restart: always
    ports:
      - '3306:3306'
